# By default types specified in commitizen/conventional-commit-types is used.
# See: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
# You can override the valid types
types:
  - feat
  - fix
  - docs
  - refactor
  - perf
  - test
  - build
  - ci
  - docker
  - chore
  - revert
  - model
