defaults:
  actions:
    queue:
      name: default
      method: rebase

queue_rules:
  - name: default
    conditions:
      - "status-success=Semantic Pull Request"
      - "status-success=Jenkins - Unit tests GPU"
      - or:
        - "label!=ci:docker"
        - "status-success=Jenkins - Docker build"
      
pull_request_rules:
  - name: "automatic merge with 2 reviews"
    conditions:
      - "base=master"
      - "label!=process:manual-merge"
      - "#changes-requested-reviews-by=0"
      - "status-success=Semantic Pull Request"
      - "status-success=Jenkins - Unit tests GPU"
      - or:
        - "label!=ci:docker"
        - "status-success=Jenkins - Docker build"
      - or:
        - "label=process:no-need-review"
        - and:
          - "#approved-reviews-by>=2"
          - "label=process:ready-to-review"
    actions:
      queue:

  - name: "request review"
    conditions:
      - "label=process:ready-to-review"
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - -merged
      - -closed
    actions:
      request_reviews:
        users:
          - Bycob
          - beniz
          - fantes

  - name: "warn on conflicts"
    conditions:
      - conflict
    actions:
      comment:
        message: "This pull request is now in conflict :("
      label:
        add:
          - conflict

  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: add ci:docker label
    conditions:
      - files~=^docker/
    actions:
      label:
        add:
            - ci:docker
            
  - name: add merge-queued label
    conditions:
      - queue-position>=0
    actions:
      label:
        add:
          - process:merge-queued
          
  - name: remove merge-queued label
    conditions:
      - queue-position<0
    actions:
      label:
        remove:
          - process:merge-queued
