from __future__ import annotations

import argparse
import shutil
import sys
import tarfile
import urllib.request
from pathlib import Path


FIXTURES = {
    "yolox_train_torch": (
        "https://www.deepdetect.com/dd/examples/torch/yolox_train_torch.tar.gz"
    ),
    "fasterrcnn_train_torch111": (
        "https://www.deepdetect.com/dd/examples/torch/"
        "fasterrcnn_train_torch111_bs2.tar.gz"
    ),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Prepare a tiny YOLOX CLI quickstart dataset"
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="directory that will receive fixtures and yolox-quickstart.yaml",
    )
    parser.add_argument(
        "--download-dir",
        type=Path,
        default=None,
        help="directory used to cache downloaded fixture archives",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace the output directory if it already exists",
    )
    return parser.parse_args()


def download(url: str, destination: Path) -> None:
    if destination.is_file():
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    print(f"Downloading {url}")
    urllib.request.urlretrieve(url, destination)


def safe_extract(archive: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    root = destination.resolve()
    with tarfile.open(archive) as tar:
        for member in tar.getmembers():
            member_path = Path(member.name)
            if member_path.is_absolute() or ".." in member_path.parts:
                raise RuntimeError(f"unsafe archive path: {member.name}")
            if member.issym() or member.islnk():
                raise RuntimeError(f"archive links are not supported: {member.name}")
            target = (root / member.name).resolve()
            if target != root and root not in target.parents:
                raise RuntimeError(f"unsafe archive path: {member.name}")
        if sys.version_info >= (3, 12):
            tar.extractall(root, filter="data")
        else:
            tar.extractall(root)


def rewrite_fixture_lists(fixture: Path, fixture_name: str) -> None:
    original_prefix = f"../examples/torch/{fixture_name}"
    replacement = str(fixture.resolve())
    for list_file in fixture.rglob("*.txt"):
        try:
            contents = list_file.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        rewritten = contents.replace(original_prefix, replacement)
        if rewritten != contents:
            list_file.write_text(rewritten, encoding="utf-8")


def find_extracted_fixture(fixtures_dir: Path, name: str) -> Path:
    candidate = fixtures_dir / name
    if candidate.is_dir():
        return candidate
    matches = sorted(path for path in fixtures_dir.rglob(name) if path.is_dir())
    if matches:
        return matches[0]
    raise FileNotFoundError(f"extracted fixture directory not found: {name}")


def find_yolox_weights(repository: Path) -> Path:
    candidates = [
        path
        for path in sorted(repository.rglob("*.pt"))
        if not path.name.startswith(("checkpoint-", "solver-"))
    ]
    if not candidates:
        raise FileNotFoundError(f"no YOLOX .pt weights found under {repository}")
    preferred = [path for path in candidates if "yolox" in path.name.lower()]
    return (preferred or candidates)[0]


def write_config(
    *,
    path: Path,
    train_data: Path,
    test_data: Path,
    weights: Path,
    repository: Path,
) -> None:
    values = {
        "train_data": str(train_data.resolve()),
        "test_data": [str(test_data.resolve())],
        "weights": str(weights.resolve()),
        "repository": str(repository.resolve()),
        "service_name": "quickstart-yolox",
        "nclasses": 2,
        "width": 640,
        "height": 640,
        "iterations": 3,
        "batch_size": 2,
        "iter_size": 2,
        "base_lr": 0.0001,
        "test_interval": 3,
        "gpu": False,
        "sync": False,
        "poll_interval": 0.5,
        "run_name": "yolox-quickstart",
        "terminal": "verbose",
        "dataset_check": "full",
        "visdom": True,
        "visdom_server": "http://localhost",
        "visdom_port": 8097,
        "visdom_offline_ok": True,
        "visdom_results": True,
        "visdom_results_count": 2,
        "visdom_results_seed": 12345,
        "confidence_threshold": 0.25,
    }
    lines = [
        "# Generated by bindings/python/scripts/prepare_cli_yolox_quickstart.py",
        f"train_data: {values['train_data']}",
        "test_data:",
        f"  - {values['test_data'][0]}",
    ]
    for key, value in values.items():
        if key in {"train_data", "test_data"}:
            continue
        if isinstance(value, bool):
            rendered = "true" if value else "false"
        elif isinstance(value, str):
            rendered = value
        else:
            rendered = str(value)
        lines.append(f"{key}: {rendered}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def first_image_from_list(path: Path) -> Path:
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        return Path(line.split()[0]).resolve()
    raise RuntimeError(f"dataset list contains no images: {path}")


def prepare(
    output: Path, *, download_dir: Path | None, force: bool
) -> tuple[Path, Path]:
    output = output.expanduser().resolve()
    if output.exists():
        if not force:
            raise FileExistsError(f"output directory already exists: {output}")
        shutil.rmtree(output)
    output.mkdir(parents=True)

    download_dir = (
        download_dir.expanduser().resolve()
        if download_dir is not None
        else output / ".downloads"
    )
    fixtures_dir = output / "fixtures"
    for name, url in FIXTURES.items():
        archive = download_dir / Path(url).name
        download(url, archive)
        safe_extract(archive, fixtures_dir)
        rewrite_fixture_lists(find_extracted_fixture(fixtures_dir, name), name)

    yolox = find_extracted_fixture(fixtures_dir, "yolox_train_torch")
    fasterrcnn = find_extracted_fixture(fixtures_dir, "fasterrcnn_train_torch111")
    train_data = fasterrcnn / "train.txt"
    test_data = fasterrcnn / "test.txt"
    weights = find_yolox_weights(yolox)
    repository = output / "model-repository"
    shutil.copytree(
        yolox,
        repository,
        ignore=shutil.ignore_patterns(
            "train.lmdb",
            "test_0.lmdb",
            "checkpoint-*.pt",
            "checkpoint-*.ptw",
            "solver-*.json",
        ),
    )

    config = output / "yolox-quickstart.yaml"
    write_config(
        path=config,
        train_data=train_data,
        test_data=test_data,
        weights=weights,
        repository=repository,
    )
    return config, first_image_from_list(test_data)


def main() -> int:
    args = parse_args()
    config, image = prepare(
        args.output, download_dir=args.download_dir, force=args.force
    )
    print(f"Config: {config}")
    print(f"Sample image: {image}")
    print()
    print("Start Visdom:")
    print("  python -m visdom.server -port 8097")
    print()
    print("Train:")
    print(f"  deepdetect train yolox --config {config} --terminal live")
    print()
    print("Infer:")
    print(
        f"  deepdetect infer yolox {image} --config {config} "
        f"--visualize --output {config.parent / 'detections.png'}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
