op {
  output: "comp_0_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_0_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 64
    ints: 64
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_0_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_0_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 64
    ints: 64
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_0_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_0_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 64
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_0_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_0_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_0_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_0_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_0_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_0_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_0_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_0_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_0_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_0_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_0_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_0_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 1024
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_10_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 256
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_10_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_10_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 1024
    ints: 256
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_10_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_10_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_10_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_10_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_10_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_11_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_11_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 1024
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_11_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_11_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 256
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_11_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_11_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 1024
    ints: 256
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_11_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_11_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_11_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_11_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_11_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_11_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_11_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_11_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_11_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_11_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_11_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_11_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_12_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_12_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 1024
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_12_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_12_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 256
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_12_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_12_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 1024
    ints: 256
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_12_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_12_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_12_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_12_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_12_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_12_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_12_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_12_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_12_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_12_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_12_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_12_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_13_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_13_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 1024
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_13_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_13_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 512
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_13_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_13_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 2048
    ints: 512
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_13_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_13_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_13_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_13_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_13_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_13_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_13_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_13_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_13_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_13_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_13_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_13_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_14_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_14_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 2048
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_14_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_14_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 512
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_14_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_14_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 2048
    ints: 512
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_14_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_14_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_14_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_14_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_14_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_14_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_14_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_14_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_14_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_14_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_14_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_14_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_15_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_15_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 2048
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_15_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_15_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 512
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_15_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_15_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 2048
    ints: 512
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_15_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_15_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_15_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_15_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_15_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_15_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_15_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_15_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_15_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_15_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_15_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_15_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "comp_1_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_1_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 64
    ints: 256
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_1_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_1_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 64
    ints: 64
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_1_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_1_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 64
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_1_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_1_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_1_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_1_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_1_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_1_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_1_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_1_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_1_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_1_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_1_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_1_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_2_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_2_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 64
    ints: 256
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_2_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_2_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 64
    ints: 64
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_2_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_2_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 64
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_2_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_2_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_2_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_2_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_2_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_2_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_2_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_2_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "comp_2_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_2_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_2_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_2_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_3_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_3_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 128
    ints: 256
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_3_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_3_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 128
    ints: 128
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_3_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_3_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 128
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_3_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_3_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_3_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_3_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_3_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_3_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_3_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_3_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_3_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_3_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_3_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_3_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_4_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_4_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 128
    ints: 512
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_4_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_4_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 128
    ints: 128
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_4_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_4_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 128
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_4_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_4_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_4_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_4_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_4_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_4_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_4_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_4_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_4_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_4_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_4_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_4_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_5_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_5_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 128
    ints: 512
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_5_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_5_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 128
    ints: 128
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_5_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_5_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 128
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_5_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_5_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_5_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_5_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_5_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_5_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_5_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_5_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_5_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_5_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_5_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_5_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_6_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_6_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 128
    ints: 512
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_6_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_6_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 128
    ints: 128
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_6_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_6_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 128
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_6_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_6_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_6_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_6_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_6_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_6_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_6_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_6_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 128
  }
}
op {
  output: "comp_6_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_6_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_6_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_6_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "comp_7_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_7_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 512
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_7_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_7_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 256
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_7_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_7_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 1024
    ints: 256
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_7_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_7_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_7_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_7_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_7_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_7_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_7_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_7_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_7_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_7_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_7_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_7_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_8_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_8_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 1024
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_8_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_8_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 256
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_8_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_8_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 1024
    ints: 256
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_8_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_8_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_8_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_8_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_8_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_8_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_8_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_8_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_8_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_8_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_8_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_8_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_9_conv_1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_9_conv_1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 1024
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_9_conv_2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_9_conv_2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 256
    ints: 3
    ints: 3
  }
}
op {
  output: "comp_9_conv_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_9_conv_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 1024
    ints: 256
    ints: 1
    ints: 1
  }
}
op {
  output: "comp_9_spatbn_1_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_9_spatbn_1_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_9_spatbn_1_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_9_spatbn_1_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_9_spatbn_2_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_9_spatbn_2_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_9_spatbn_2_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_9_spatbn_2_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "comp_9_spatbn_3_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_9_spatbn_3_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_9_spatbn_3_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "comp_9_spatbn_3_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "conv1_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "conv1_spatbn_relu_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "conv1_spatbn_relu_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "conv1_spatbn_relu_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "conv1_spatbn_relu_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 64
  }
}
op {
  output: "conv1_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 64
    ints: 3
    ints: 7
    ints: 7
  }
}
op {
  output: "last_out_L2_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 2
  }
}
op {
  output: "last_out_L2_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 2
    ints: 2048
  }
}
op {
  output: "shortcut_projection_0_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "shortcut_projection_0_spatbn_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "shortcut_projection_0_spatbn_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "shortcut_projection_0_spatbn_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "shortcut_projection_0_spatbn_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 256
  }
}
op {
  output: "shortcut_projection_0_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 256
    ints: 64
    ints: 1
    ints: 1
  }
}
op {
  output: "shortcut_projection_13_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "shortcut_projection_13_spatbn_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "shortcut_projection_13_spatbn_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "shortcut_projection_13_spatbn_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "shortcut_projection_13_spatbn_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 2048
  }
}
op {
  output: "shortcut_projection_13_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 2048
    ints: 1024
    ints: 1
    ints: 1
  }
}
op {
  output: "shortcut_projection_3_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "shortcut_projection_3_spatbn_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "shortcut_projection_3_spatbn_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "shortcut_projection_3_spatbn_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "shortcut_projection_3_spatbn_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 512
  }
}
op {
  output: "shortcut_projection_3_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 512
    ints: 256
    ints: 1
    ints: 1
  }
}
op {
  output: "shortcut_projection_7_b"
  type: "ConstantFill"
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "shortcut_projection_7_spatbn_b"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "shortcut_projection_7_spatbn_riv"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "shortcut_projection_7_spatbn_rm"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 0
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "shortcut_projection_7_spatbn_s"
  type: "ConstantFill"
  arg {
    name: "value"
    f: 1
  }
  arg {
    name: "shape"
    ints: 1024
  }
}
op {
  output: "shortcut_projection_7_w"
  type: "XavierFill"
  arg {
    name: "shape"
    ints: 1024
    ints: 512
    ints: 1
    ints: 1
  }
}
