name: "resnet50"
op {
  input: "data"
  input: "conv1_w"
  output: "conv1"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 7
  }
  arg {
    name: "pad"
    i: 3
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "conv1"
  input: "res_conv1_bn_s"
  input: "res_conv1_bn_b"
  input: "res_conv1_bn_rm"
  input: "res_conv1_bn_riv"
  output: "res_conv1_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res_conv1_bn"
  output: "res_conv1_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res_conv1_bn"
  output: "pool1"
  name: ""
  type: "MaxPool"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "stride"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "pool1"
  input: "res2_0_branch2a_w"
  output: "res2_0_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2a"
  input: "res2_0_branch2a_bn_s"
  input: "res2_0_branch2a_bn_b"
  input: "res2_0_branch2a_bn_rm"
  input: "res2_0_branch2a_bn_riv"
  output: "res2_0_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2a_bn"
  output: "res2_0_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2a_bn"
  input: "res2_0_branch2b_w"
  output: "res2_0_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2b"
  input: "res2_0_branch2b_bn_s"
  input: "res2_0_branch2b_bn_b"
  input: "res2_0_branch2b_bn_rm"
  input: "res2_0_branch2b_bn_riv"
  output: "res2_0_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2b_bn"
  output: "res2_0_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2b_bn"
  input: "res2_0_branch2c_w"
  output: "res2_0_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2c"
  input: "res2_0_branch2c_bn_s"
  input: "res2_0_branch2c_bn_b"
  input: "res2_0_branch2c_bn_rm"
  input: "res2_0_branch2c_bn_riv"
  output: "res2_0_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "pool1"
  input: "res2_0_branch1_w"
  output: "res2_0_branch1"
  name: ""
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "kernel"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch1"
  input: "res2_0_branch1_bn_s"
  input: "res2_0_branch1_bn_b"
  input: "res2_0_branch1_bn_rm"
  input: "res2_0_branch1_bn_riv"
  output: "res2_0_branch1_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2c_bn"
  input: "res2_0_branch1_bn"
  output: "res2_0_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2c_bn"
  output: "res2_0_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2c_bn"
  input: "res2_1_branch2a_w"
  output: "res2_1_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2a"
  input: "res2_1_branch2a_bn_s"
  input: "res2_1_branch2a_bn_b"
  input: "res2_1_branch2a_bn_rm"
  input: "res2_1_branch2a_bn_riv"
  output: "res2_1_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2a_bn"
  output: "res2_1_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2a_bn"
  input: "res2_1_branch2b_w"
  output: "res2_1_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2b"
  input: "res2_1_branch2b_bn_s"
  input: "res2_1_branch2b_bn_b"
  input: "res2_1_branch2b_bn_rm"
  input: "res2_1_branch2b_bn_riv"
  output: "res2_1_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2b_bn"
  output: "res2_1_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2b_bn"
  input: "res2_1_branch2c_w"
  output: "res2_1_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2c"
  input: "res2_1_branch2c_bn_s"
  input: "res2_1_branch2c_bn_b"
  input: "res2_1_branch2c_bn_rm"
  input: "res2_1_branch2c_bn_riv"
  output: "res2_1_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2c_bn"
  input: "res2_0_branch2c_bn"
  output: "res2_1_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2c_bn"
  output: "res2_1_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2c_bn"
  input: "res2_2_branch2a_w"
  output: "res2_2_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2a"
  input: "res2_2_branch2a_bn_s"
  input: "res2_2_branch2a_bn_b"
  input: "res2_2_branch2a_bn_rm"
  input: "res2_2_branch2a_bn_riv"
  output: "res2_2_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2a_bn"
  output: "res2_2_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2a_bn"
  input: "res2_2_branch2b_w"
  output: "res2_2_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2b"
  input: "res2_2_branch2b_bn_s"
  input: "res2_2_branch2b_bn_b"
  input: "res2_2_branch2b_bn_rm"
  input: "res2_2_branch2b_bn_riv"
  output: "res2_2_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2b_bn"
  output: "res2_2_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2b_bn"
  input: "res2_2_branch2c_w"
  output: "res2_2_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2c"
  input: "res2_2_branch2c_bn_s"
  input: "res2_2_branch2c_bn_b"
  input: "res2_2_branch2c_bn_rm"
  input: "res2_2_branch2c_bn_riv"
  output: "res2_2_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2c_bn"
  input: "res2_1_branch2c_bn"
  output: "res2_2_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2c_bn"
  output: "res2_2_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2c_bn"
  input: "res3_0_branch2a_w"
  output: "res3_0_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2a"
  input: "res3_0_branch2a_bn_s"
  input: "res3_0_branch2a_bn_b"
  input: "res3_0_branch2a_bn_rm"
  input: "res3_0_branch2a_bn_riv"
  output: "res3_0_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2a_bn"
  output: "res3_0_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2a_bn"
  input: "res3_0_branch2b_w"
  output: "res3_0_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2b"
  input: "res3_0_branch2b_bn_s"
  input: "res3_0_branch2b_bn_b"
  input: "res3_0_branch2b_bn_rm"
  input: "res3_0_branch2b_bn_riv"
  output: "res3_0_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2b_bn"
  output: "res3_0_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2b_bn"
  input: "res3_0_branch2c_w"
  output: "res3_0_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2c"
  input: "res3_0_branch2c_bn_s"
  input: "res3_0_branch2c_bn_b"
  input: "res3_0_branch2c_bn_rm"
  input: "res3_0_branch2c_bn_riv"
  output: "res3_0_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2c_bn"
  input: "res3_0_branch1_w"
  output: "res3_0_branch1"
  name: ""
  type: "Conv"
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "kernel"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch1"
  input: "res3_0_branch1_bn_s"
  input: "res3_0_branch1_bn_b"
  input: "res3_0_branch1_bn_rm"
  input: "res3_0_branch1_bn_riv"
  output: "res3_0_branch1_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2c_bn"
  input: "res3_0_branch1_bn"
  output: "res3_0_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2c_bn"
  output: "res3_0_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2c_bn"
  input: "res3_1_branch2a_w"
  output: "res3_1_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2a"
  input: "res3_1_branch2a_bn_s"
  input: "res3_1_branch2a_bn_b"
  input: "res3_1_branch2a_bn_rm"
  input: "res3_1_branch2a_bn_riv"
  output: "res3_1_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2a_bn"
  output: "res3_1_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2a_bn"
  input: "res3_1_branch2b_w"
  output: "res3_1_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2b"
  input: "res3_1_branch2b_bn_s"
  input: "res3_1_branch2b_bn_b"
  input: "res3_1_branch2b_bn_rm"
  input: "res3_1_branch2b_bn_riv"
  output: "res3_1_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2b_bn"
  output: "res3_1_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2b_bn"
  input: "res3_1_branch2c_w"
  output: "res3_1_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2c"
  input: "res3_1_branch2c_bn_s"
  input: "res3_1_branch2c_bn_b"
  input: "res3_1_branch2c_bn_rm"
  input: "res3_1_branch2c_bn_riv"
  output: "res3_1_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2c_bn"
  input: "res3_0_branch2c_bn"
  output: "res3_1_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2c_bn"
  output: "res3_1_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2c_bn"
  input: "res3_2_branch2a_w"
  output: "res3_2_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2a"
  input: "res3_2_branch2a_bn_s"
  input: "res3_2_branch2a_bn_b"
  input: "res3_2_branch2a_bn_rm"
  input: "res3_2_branch2a_bn_riv"
  output: "res3_2_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2a_bn"
  output: "res3_2_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2a_bn"
  input: "res3_2_branch2b_w"
  output: "res3_2_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2b"
  input: "res3_2_branch2b_bn_s"
  input: "res3_2_branch2b_bn_b"
  input: "res3_2_branch2b_bn_rm"
  input: "res3_2_branch2b_bn_riv"
  output: "res3_2_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2b_bn"
  output: "res3_2_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2b_bn"
  input: "res3_2_branch2c_w"
  output: "res3_2_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2c"
  input: "res3_2_branch2c_bn_s"
  input: "res3_2_branch2c_bn_b"
  input: "res3_2_branch2c_bn_rm"
  input: "res3_2_branch2c_bn_riv"
  output: "res3_2_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2c_bn"
  input: "res3_1_branch2c_bn"
  output: "res3_2_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2c_bn"
  output: "res3_2_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2c_bn"
  input: "res3_3_branch2a_w"
  output: "res3_3_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2a"
  input: "res3_3_branch2a_bn_s"
  input: "res3_3_branch2a_bn_b"
  input: "res3_3_branch2a_bn_rm"
  input: "res3_3_branch2a_bn_riv"
  output: "res3_3_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2a_bn"
  output: "res3_3_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2a_bn"
  input: "res3_3_branch2b_w"
  output: "res3_3_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2b"
  input: "res3_3_branch2b_bn_s"
  input: "res3_3_branch2b_bn_b"
  input: "res3_3_branch2b_bn_rm"
  input: "res3_3_branch2b_bn_riv"
  output: "res3_3_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2b_bn"
  output: "res3_3_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2b_bn"
  input: "res3_3_branch2c_w"
  output: "res3_3_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2c"
  input: "res3_3_branch2c_bn_s"
  input: "res3_3_branch2c_bn_b"
  input: "res3_3_branch2c_bn_rm"
  input: "res3_3_branch2c_bn_riv"
  output: "res3_3_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2c_bn"
  input: "res3_2_branch2c_bn"
  output: "res3_3_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2c_bn"
  output: "res3_3_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2c_bn"
  input: "res4_0_branch2a_w"
  output: "res4_0_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2a"
  input: "res4_0_branch2a_bn_s"
  input: "res4_0_branch2a_bn_b"
  input: "res4_0_branch2a_bn_rm"
  input: "res4_0_branch2a_bn_riv"
  output: "res4_0_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2a_bn"
  output: "res4_0_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2a_bn"
  input: "res4_0_branch2b_w"
  output: "res4_0_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2b"
  input: "res4_0_branch2b_bn_s"
  input: "res4_0_branch2b_bn_b"
  input: "res4_0_branch2b_bn_rm"
  input: "res4_0_branch2b_bn_riv"
  output: "res4_0_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2b_bn"
  output: "res4_0_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2b_bn"
  input: "res4_0_branch2c_w"
  output: "res4_0_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2c"
  input: "res4_0_branch2c_bn_s"
  input: "res4_0_branch2c_bn_b"
  input: "res4_0_branch2c_bn_rm"
  input: "res4_0_branch2c_bn_riv"
  output: "res4_0_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2c_bn"
  input: "res4_0_branch1_w"
  output: "res4_0_branch1"
  name: ""
  type: "Conv"
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "kernel"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch1"
  input: "res4_0_branch1_bn_s"
  input: "res4_0_branch1_bn_b"
  input: "res4_0_branch1_bn_rm"
  input: "res4_0_branch1_bn_riv"
  output: "res4_0_branch1_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2c_bn"
  input: "res4_0_branch1_bn"
  output: "res4_0_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2c_bn"
  output: "res4_0_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2c_bn"
  input: "res4_1_branch2a_w"
  output: "res4_1_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2a"
  input: "res4_1_branch2a_bn_s"
  input: "res4_1_branch2a_bn_b"
  input: "res4_1_branch2a_bn_rm"
  input: "res4_1_branch2a_bn_riv"
  output: "res4_1_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2a_bn"
  output: "res4_1_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2a_bn"
  input: "res4_1_branch2b_w"
  output: "res4_1_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2b"
  input: "res4_1_branch2b_bn_s"
  input: "res4_1_branch2b_bn_b"
  input: "res4_1_branch2b_bn_rm"
  input: "res4_1_branch2b_bn_riv"
  output: "res4_1_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2b_bn"
  output: "res4_1_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2b_bn"
  input: "res4_1_branch2c_w"
  output: "res4_1_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2c"
  input: "res4_1_branch2c_bn_s"
  input: "res4_1_branch2c_bn_b"
  input: "res4_1_branch2c_bn_rm"
  input: "res4_1_branch2c_bn_riv"
  output: "res4_1_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2c_bn"
  input: "res4_0_branch2c_bn"
  output: "res4_1_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2c_bn"
  output: "res4_1_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2c_bn"
  input: "res4_2_branch2a_w"
  output: "res4_2_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2a"
  input: "res4_2_branch2a_bn_s"
  input: "res4_2_branch2a_bn_b"
  input: "res4_2_branch2a_bn_rm"
  input: "res4_2_branch2a_bn_riv"
  output: "res4_2_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2a_bn"
  output: "res4_2_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2a_bn"
  input: "res4_2_branch2b_w"
  output: "res4_2_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2b"
  input: "res4_2_branch2b_bn_s"
  input: "res4_2_branch2b_bn_b"
  input: "res4_2_branch2b_bn_rm"
  input: "res4_2_branch2b_bn_riv"
  output: "res4_2_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2b_bn"
  output: "res4_2_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2b_bn"
  input: "res4_2_branch2c_w"
  output: "res4_2_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2c"
  input: "res4_2_branch2c_bn_s"
  input: "res4_2_branch2c_bn_b"
  input: "res4_2_branch2c_bn_rm"
  input: "res4_2_branch2c_bn_riv"
  output: "res4_2_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2c_bn"
  input: "res4_1_branch2c_bn"
  output: "res4_2_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2c_bn"
  output: "res4_2_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2c_bn"
  input: "res4_3_branch2a_w"
  output: "res4_3_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2a"
  input: "res4_3_branch2a_bn_s"
  input: "res4_3_branch2a_bn_b"
  input: "res4_3_branch2a_bn_rm"
  input: "res4_3_branch2a_bn_riv"
  output: "res4_3_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2a_bn"
  output: "res4_3_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2a_bn"
  input: "res4_3_branch2b_w"
  output: "res4_3_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2b"
  input: "res4_3_branch2b_bn_s"
  input: "res4_3_branch2b_bn_b"
  input: "res4_3_branch2b_bn_rm"
  input: "res4_3_branch2b_bn_riv"
  output: "res4_3_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2b_bn"
  output: "res4_3_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2b_bn"
  input: "res4_3_branch2c_w"
  output: "res4_3_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2c"
  input: "res4_3_branch2c_bn_s"
  input: "res4_3_branch2c_bn_b"
  input: "res4_3_branch2c_bn_rm"
  input: "res4_3_branch2c_bn_riv"
  output: "res4_3_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2c_bn"
  input: "res4_2_branch2c_bn"
  output: "res4_3_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2c_bn"
  output: "res4_3_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2c_bn"
  input: "res4_4_branch2a_w"
  output: "res4_4_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_4_branch2a"
  input: "res4_4_branch2a_bn_s"
  input: "res4_4_branch2a_bn_b"
  input: "res4_4_branch2a_bn_rm"
  input: "res4_4_branch2a_bn_riv"
  output: "res4_4_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_4_branch2a_bn"
  output: "res4_4_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_4_branch2a_bn"
  input: "res4_4_branch2b_w"
  output: "res4_4_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_4_branch2b"
  input: "res4_4_branch2b_bn_s"
  input: "res4_4_branch2b_bn_b"
  input: "res4_4_branch2b_bn_rm"
  input: "res4_4_branch2b_bn_riv"
  output: "res4_4_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_4_branch2b_bn"
  output: "res4_4_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_4_branch2b_bn"
  input: "res4_4_branch2c_w"
  output: "res4_4_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_4_branch2c"
  input: "res4_4_branch2c_bn_s"
  input: "res4_4_branch2c_bn_b"
  input: "res4_4_branch2c_bn_rm"
  input: "res4_4_branch2c_bn_riv"
  output: "res4_4_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_4_branch2c_bn"
  input: "res4_3_branch2c_bn"
  output: "res4_4_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_4_branch2c_bn"
  output: "res4_4_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_4_branch2c_bn"
  input: "res4_5_branch2a_w"
  output: "res4_5_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2a"
  input: "res4_5_branch2a_bn_s"
  input: "res4_5_branch2a_bn_b"
  input: "res4_5_branch2a_bn_rm"
  input: "res4_5_branch2a_bn_riv"
  output: "res4_5_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2a_bn"
  output: "res4_5_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2a_bn"
  input: "res4_5_branch2b_w"
  output: "res4_5_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2b"
  input: "res4_5_branch2b_bn_s"
  input: "res4_5_branch2b_bn_b"
  input: "res4_5_branch2b_bn_rm"
  input: "res4_5_branch2b_bn_riv"
  output: "res4_5_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2b_bn"
  output: "res4_5_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2b_bn"
  input: "res4_5_branch2c_w"
  output: "res4_5_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2c"
  input: "res4_5_branch2c_bn_s"
  input: "res4_5_branch2c_bn_b"
  input: "res4_5_branch2c_bn_rm"
  input: "res4_5_branch2c_bn_riv"
  output: "res4_5_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2c_bn"
  input: "res4_4_branch2c_bn"
  output: "res4_5_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2c_bn"
  output: "res4_5_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2c_bn"
  input: "res5_0_branch2a_w"
  output: "res5_0_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch2a"
  input: "res5_0_branch2a_bn_s"
  input: "res5_0_branch2a_bn_b"
  input: "res5_0_branch2a_bn_rm"
  input: "res5_0_branch2a_bn_riv"
  output: "res5_0_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch2a_bn"
  output: "res5_0_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch2a_bn"
  input: "res5_0_branch2b_w"
  output: "res5_0_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch2b"
  input: "res5_0_branch2b_bn_s"
  input: "res5_0_branch2b_bn_b"
  input: "res5_0_branch2b_bn_rm"
  input: "res5_0_branch2b_bn_riv"
  output: "res5_0_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch2b_bn"
  output: "res5_0_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch2b_bn"
  input: "res5_0_branch2c_w"
  output: "res5_0_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch2c"
  input: "res5_0_branch2c_bn_s"
  input: "res5_0_branch2c_bn_b"
  input: "res5_0_branch2c_bn_rm"
  input: "res5_0_branch2c_bn_riv"
  output: "res5_0_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_5_branch2c_bn"
  input: "res5_0_branch1_w"
  output: "res5_0_branch1"
  name: ""
  type: "Conv"
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "kernel"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch1"
  input: "res5_0_branch1_bn_s"
  input: "res5_0_branch1_bn_b"
  input: "res5_0_branch1_bn_rm"
  input: "res5_0_branch1_bn_riv"
  output: "res5_0_branch1_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch2c_bn"
  input: "res5_0_branch1_bn"
  output: "res5_0_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch2c_bn"
  output: "res5_0_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_0_branch2c_bn"
  input: "res5_1_branch2a_w"
  output: "res5_1_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_1_branch2a"
  input: "res5_1_branch2a_bn_s"
  input: "res5_1_branch2a_bn_b"
  input: "res5_1_branch2a_bn_rm"
  input: "res5_1_branch2a_bn_riv"
  output: "res5_1_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_1_branch2a_bn"
  output: "res5_1_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_1_branch2a_bn"
  input: "res5_1_branch2b_w"
  output: "res5_1_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_1_branch2b"
  input: "res5_1_branch2b_bn_s"
  input: "res5_1_branch2b_bn_b"
  input: "res5_1_branch2b_bn_rm"
  input: "res5_1_branch2b_bn_riv"
  output: "res5_1_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_1_branch2b_bn"
  output: "res5_1_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_1_branch2b_bn"
  input: "res5_1_branch2c_w"
  output: "res5_1_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_1_branch2c"
  input: "res5_1_branch2c_bn_s"
  input: "res5_1_branch2c_bn_b"
  input: "res5_1_branch2c_bn_rm"
  input: "res5_1_branch2c_bn_riv"
  output: "res5_1_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_1_branch2c_bn"
  input: "res5_0_branch2c_bn"
  output: "res5_1_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_1_branch2c_bn"
  output: "res5_1_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_1_branch2c_bn"
  input: "res5_2_branch2a_w"
  output: "res5_2_branch2a"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_2_branch2a"
  input: "res5_2_branch2a_bn_s"
  input: "res5_2_branch2a_bn_b"
  input: "res5_2_branch2a_bn_rm"
  input: "res5_2_branch2a_bn_riv"
  output: "res5_2_branch2a_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_2_branch2a_bn"
  output: "res5_2_branch2a_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_2_branch2a_bn"
  input: "res5_2_branch2b_w"
  output: "res5_2_branch2b"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_2_branch2b"
  input: "res5_2_branch2b_bn_s"
  input: "res5_2_branch2b_bn_b"
  input: "res5_2_branch2b_bn_rm"
  input: "res5_2_branch2b_bn_riv"
  output: "res5_2_branch2b_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_2_branch2b_bn"
  output: "res5_2_branch2b_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_2_branch2b_bn"
  input: "res5_2_branch2c_w"
  output: "res5_2_branch2c"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_2_branch2c"
  input: "res5_2_branch2c_bn_s"
  input: "res5_2_branch2c_bn_b"
  input: "res5_2_branch2c_bn_rm"
  input: "res5_2_branch2c_bn_riv"
  output: "res5_2_branch2c_bn"
  name: ""
  type: "SpatialBN"
  arg {
    name: "epsilon"
    f: 1.00000007e-05
  }
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res5_2_branch2c_bn"
  input: "res5_1_branch2c_bn"
  output: "res5_2_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_2_branch2c_bn"
  output: "res5_2_branch2c_bn"
  name: ""
  type: "Relu"
  device_option {
  }
  engine: ""
}
op {
  input: "res5_2_branch2c_bn"
  output: "pool5"
  name: ""
  type: "AveragePool"
  arg {
    name: "kernel"
    i: 7
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "pool5"
  input: "pred_w"
  input: "pred_b"
  output: "pred"
  name: ""
  type: "FC"
  device_option {
  }
  engine: ""
}
op {
  input: "pred"
  output: "softmax"
  name: ""
  type: "Softmax"
  device_option {
  }
  engine: ""
}
external_input: "data"
external_input: "conv1_w"
external_input: "res_conv1_bn_s"
external_input: "res_conv1_bn_b"
external_input: "res2_0_branch2a_w"
external_input: "res2_0_branch2a_bn_s"
external_input: "res2_0_branch2a_bn_b"
external_input: "res2_0_branch2b_w"
external_input: "res2_0_branch2b_bn_s"
external_input: "res2_0_branch2b_bn_b"
external_input: "res2_0_branch2c_w"
external_input: "res2_0_branch2c_bn_s"
external_input: "res2_0_branch2c_bn_b"
external_input: "res2_0_branch1_w"
external_input: "res2_0_branch1_bn_s"
external_input: "res2_0_branch1_bn_b"
external_input: "res2_1_branch2a_w"
external_input: "res2_1_branch2a_bn_s"
external_input: "res2_1_branch2a_bn_b"
external_input: "res2_1_branch2b_w"
external_input: "res2_1_branch2b_bn_s"
external_input: "res2_1_branch2b_bn_b"
external_input: "res2_1_branch2c_w"
external_input: "res2_1_branch2c_bn_s"
external_input: "res2_1_branch2c_bn_b"
external_input: "res2_2_branch2a_w"
external_input: "res2_2_branch2a_bn_s"
external_input: "res2_2_branch2a_bn_b"
external_input: "res2_2_branch2b_w"
external_input: "res2_2_branch2b_bn_s"
external_input: "res2_2_branch2b_bn_b"
external_input: "res2_2_branch2c_w"
external_input: "res2_2_branch2c_bn_s"
external_input: "res2_2_branch2c_bn_b"
external_input: "res3_0_branch2a_w"
external_input: "res3_0_branch2a_bn_s"
external_input: "res3_0_branch2a_bn_b"
external_input: "res3_0_branch2b_w"
external_input: "res3_0_branch2b_bn_s"
external_input: "res3_0_branch2b_bn_b"
external_input: "res3_0_branch2c_w"
external_input: "res3_0_branch2c_bn_s"
external_input: "res3_0_branch2c_bn_b"
external_input: "res3_0_branch1_w"
external_input: "res3_0_branch1_bn_s"
external_input: "res3_0_branch1_bn_b"
external_input: "res3_1_branch2a_w"
external_input: "res3_1_branch2a_bn_s"
external_input: "res3_1_branch2a_bn_b"
external_input: "res3_1_branch2b_w"
external_input: "res3_1_branch2b_bn_s"
external_input: "res3_1_branch2b_bn_b"
external_input: "res3_1_branch2c_w"
external_input: "res3_1_branch2c_bn_s"
external_input: "res3_1_branch2c_bn_b"
external_input: "res3_2_branch2a_w"
external_input: "res3_2_branch2a_bn_s"
external_input: "res3_2_branch2a_bn_b"
external_input: "res3_2_branch2b_w"
external_input: "res3_2_branch2b_bn_s"
external_input: "res3_2_branch2b_bn_b"
external_input: "res3_2_branch2c_w"
external_input: "res3_2_branch2c_bn_s"
external_input: "res3_2_branch2c_bn_b"
external_input: "res3_3_branch2a_w"
external_input: "res3_3_branch2a_bn_s"
external_input: "res3_3_branch2a_bn_b"
external_input: "res3_3_branch2b_w"
external_input: "res3_3_branch2b_bn_s"
external_input: "res3_3_branch2b_bn_b"
external_input: "res3_3_branch2c_w"
external_input: "res3_3_branch2c_bn_s"
external_input: "res3_3_branch2c_bn_b"
external_input: "res4_0_branch2a_w"
external_input: "res4_0_branch2a_bn_s"
external_input: "res4_0_branch2a_bn_b"
external_input: "res4_0_branch2b_w"
external_input: "res4_0_branch2b_bn_s"
external_input: "res4_0_branch2b_bn_b"
external_input: "res4_0_branch2c_w"
external_input: "res4_0_branch2c_bn_s"
external_input: "res4_0_branch2c_bn_b"
external_input: "res4_0_branch1_w"
external_input: "res4_0_branch1_bn_s"
external_input: "res4_0_branch1_bn_b"
external_input: "res4_1_branch2a_w"
external_input: "res4_1_branch2a_bn_s"
external_input: "res4_1_branch2a_bn_b"
external_input: "res4_1_branch2b_w"
external_input: "res4_1_branch2b_bn_s"
external_input: "res4_1_branch2b_bn_b"
external_input: "res4_1_branch2c_w"
external_input: "res4_1_branch2c_bn_s"
external_input: "res4_1_branch2c_bn_b"
external_input: "res4_2_branch2a_w"
external_input: "res4_2_branch2a_bn_s"
external_input: "res4_2_branch2a_bn_b"
external_input: "res4_2_branch2b_w"
external_input: "res4_2_branch2b_bn_s"
external_input: "res4_2_branch2b_bn_b"
external_input: "res4_2_branch2c_w"
external_input: "res4_2_branch2c_bn_s"
external_input: "res4_2_branch2c_bn_b"
external_input: "res4_3_branch2a_w"
external_input: "res4_3_branch2a_bn_s"
external_input: "res4_3_branch2a_bn_b"
external_input: "res4_3_branch2b_w"
external_input: "res4_3_branch2b_bn_s"
external_input: "res4_3_branch2b_bn_b"
external_input: "res4_3_branch2c_w"
external_input: "res4_3_branch2c_bn_s"
external_input: "res4_3_branch2c_bn_b"
external_input: "res4_4_branch2a_w"
external_input: "res4_4_branch2a_bn_s"
external_input: "res4_4_branch2a_bn_b"
external_input: "res4_4_branch2b_w"
external_input: "res4_4_branch2b_bn_s"
external_input: "res4_4_branch2b_bn_b"
external_input: "res4_4_branch2c_w"
external_input: "res4_4_branch2c_bn_s"
external_input: "res4_4_branch2c_bn_b"
external_input: "res4_5_branch2a_w"
external_input: "res4_5_branch2a_bn_s"
external_input: "res4_5_branch2a_bn_b"
external_input: "res4_5_branch2b_w"
external_input: "res4_5_branch2b_bn_s"
external_input: "res4_5_branch2b_bn_b"
external_input: "res4_5_branch2c_w"
external_input: "res4_5_branch2c_bn_s"
external_input: "res4_5_branch2c_bn_b"
external_input: "res5_0_branch2a_w"
external_input: "res5_0_branch2a_bn_s"
external_input: "res5_0_branch2a_bn_b"
external_input: "res5_0_branch2b_w"
external_input: "res5_0_branch2b_bn_s"
external_input: "res5_0_branch2b_bn_b"
external_input: "res5_0_branch2c_w"
external_input: "res5_0_branch2c_bn_s"
external_input: "res5_0_branch2c_bn_b"
external_input: "res5_0_branch1_w"
external_input: "res5_0_branch1_bn_s"
external_input: "res5_0_branch1_bn_b"
external_input: "res5_1_branch2a_w"
external_input: "res5_1_branch2a_bn_s"
external_input: "res5_1_branch2a_bn_b"
external_input: "res5_1_branch2b_w"
external_input: "res5_1_branch2b_bn_s"
external_input: "res5_1_branch2b_bn_b"
external_input: "res5_1_branch2c_w"
external_input: "res5_1_branch2c_bn_s"
external_input: "res5_1_branch2c_bn_b"
external_input: "res5_2_branch2a_w"
external_input: "res5_2_branch2a_bn_s"
external_input: "res5_2_branch2a_bn_b"
external_input: "res5_2_branch2b_w"
external_input: "res5_2_branch2b_bn_s"
external_input: "res5_2_branch2b_bn_b"
external_input: "res5_2_branch2c_w"
external_input: "res5_2_branch2c_bn_s"
external_input: "res5_2_branch2c_bn_b"
external_input: "pred_w"
external_input: "pred_b"
external_input: "res_conv1_bn_rm"
external_input: "res_conv1_bn_riv"
external_input: "res2_0_branch2a_bn_rm"
external_input: "res2_0_branch2a_bn_riv"
external_input: "res2_0_branch2b_bn_rm"
external_input: "res2_0_branch2b_bn_riv"
external_input: "res2_0_branch2c_bn_rm"
external_input: "res2_0_branch2c_bn_riv"
external_input: "res2_0_branch1_bn_rm"
external_input: "res2_0_branch1_bn_riv"
external_input: "res2_1_branch2a_bn_rm"
external_input: "res2_1_branch2a_bn_riv"
external_input: "res2_1_branch2b_bn_rm"
external_input: "res2_1_branch2b_bn_riv"
external_input: "res2_1_branch2c_bn_rm"
external_input: "res2_1_branch2c_bn_riv"
external_input: "res2_2_branch2a_bn_rm"
external_input: "res2_2_branch2a_bn_riv"
external_input: "res2_2_branch2b_bn_rm"
external_input: "res2_2_branch2b_bn_riv"
external_input: "res2_2_branch2c_bn_rm"
external_input: "res2_2_branch2c_bn_riv"
external_input: "res3_0_branch2a_bn_rm"
external_input: "res3_0_branch2a_bn_riv"
external_input: "res3_0_branch2b_bn_rm"
external_input: "res3_0_branch2b_bn_riv"
external_input: "res3_0_branch2c_bn_rm"
external_input: "res3_0_branch2c_bn_riv"
external_input: "res3_0_branch1_bn_rm"
external_input: "res3_0_branch1_bn_riv"
external_input: "res3_1_branch2a_bn_rm"
external_input: "res3_1_branch2a_bn_riv"
external_input: "res3_1_branch2b_bn_rm"
external_input: "res3_1_branch2b_bn_riv"
external_input: "res3_1_branch2c_bn_rm"
external_input: "res3_1_branch2c_bn_riv"
external_input: "res3_2_branch2a_bn_rm"
external_input: "res3_2_branch2a_bn_riv"
external_input: "res3_2_branch2b_bn_rm"
external_input: "res3_2_branch2b_bn_riv"
external_input: "res3_2_branch2c_bn_rm"
external_input: "res3_2_branch2c_bn_riv"
external_input: "res3_3_branch2a_bn_rm"
external_input: "res3_3_branch2a_bn_riv"
external_input: "res3_3_branch2b_bn_rm"
external_input: "res3_3_branch2b_bn_riv"
external_input: "res3_3_branch2c_bn_rm"
external_input: "res3_3_branch2c_bn_riv"
external_input: "res4_0_branch2a_bn_rm"
external_input: "res4_0_branch2a_bn_riv"
external_input: "res4_0_branch2b_bn_rm"
external_input: "res4_0_branch2b_bn_riv"
external_input: "res4_0_branch2c_bn_rm"
external_input: "res4_0_branch2c_bn_riv"
external_input: "res4_0_branch1_bn_rm"
external_input: "res4_0_branch1_bn_riv"
external_input: "res4_1_branch2a_bn_rm"
external_input: "res4_1_branch2a_bn_riv"
external_input: "res4_1_branch2b_bn_rm"
external_input: "res4_1_branch2b_bn_riv"
external_input: "res4_1_branch2c_bn_rm"
external_input: "res4_1_branch2c_bn_riv"
external_input: "res4_2_branch2a_bn_rm"
external_input: "res4_2_branch2a_bn_riv"
external_input: "res4_2_branch2b_bn_rm"
external_input: "res4_2_branch2b_bn_riv"
external_input: "res4_2_branch2c_bn_rm"
external_input: "res4_2_branch2c_bn_riv"
external_input: "res4_3_branch2a_bn_rm"
external_input: "res4_3_branch2a_bn_riv"
external_input: "res4_3_branch2b_bn_rm"
external_input: "res4_3_branch2b_bn_riv"
external_input: "res4_3_branch2c_bn_rm"
external_input: "res4_3_branch2c_bn_riv"
external_input: "res4_4_branch2a_bn_rm"
external_input: "res4_4_branch2a_bn_riv"
external_input: "res4_4_branch2b_bn_rm"
external_input: "res4_4_branch2b_bn_riv"
external_input: "res4_4_branch2c_bn_rm"
external_input: "res4_4_branch2c_bn_riv"
external_input: "res4_5_branch2a_bn_rm"
external_input: "res4_5_branch2a_bn_riv"
external_input: "res4_5_branch2b_bn_rm"
external_input: "res4_5_branch2b_bn_riv"
external_input: "res4_5_branch2c_bn_rm"
external_input: "res4_5_branch2c_bn_riv"
external_input: "res5_0_branch2a_bn_rm"
external_input: "res5_0_branch2a_bn_riv"
external_input: "res5_0_branch2b_bn_rm"
external_input: "res5_0_branch2b_bn_riv"
external_input: "res5_0_branch2c_bn_rm"
external_input: "res5_0_branch2c_bn_riv"
external_input: "res5_0_branch1_bn_rm"
external_input: "res5_0_branch1_bn_riv"
external_input: "res5_1_branch2a_bn_rm"
external_input: "res5_1_branch2a_bn_riv"
external_input: "res5_1_branch2b_bn_rm"
external_input: "res5_1_branch2b_bn_riv"
external_input: "res5_1_branch2c_bn_rm"
external_input: "res5_1_branch2c_bn_riv"
external_input: "res5_2_branch2a_bn_rm"
external_input: "res5_2_branch2a_bn_riv"
external_input: "res5_2_branch2b_bn_rm"
external_input: "res5_2_branch2b_bn_riv"
external_input: "res5_2_branch2c_bn_rm"
external_input: "res5_2_branch2c_bn_riv"
external_output: "softmax"
